### ISSUE TITLE
Error in get-stats.py

### ISSUE THREAD

**Issue by Montiemedia** [wekan/wekan-stats#4]
Hi there,

i´ve got the following error:

 ./get-stats.py --board Test
Traceback (most recent call last):
  File "./get-stats.py", line 17, in <module>
    from terminaltables import AsciiTable
ImportError: No module named terminaltables

 ./get-stats.py -h
Traceback (most recent call last):
  File "./get-stats.py", line 17, in <module>
    from terminaltables import AsciiTable
ImportError: No module named terminaltables

------------------------------------------
Did you test in newest Wekan?: yes
Wekan version: 1.50.0
If this is about old version of Wekan, what upgrade problem you have?: No
Operating System: RHEl 7.5
Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): no Webserver
Node Version: 8.12.0
MongoDB Version: latest from snap

**Comment by fmonthel** [comment]
Hi

Could you run "pip install terminaltables" and try again ?
Thanks
