### ISSUE TITLE
wekan-stats with private board

### ISSUE THREAD

**Issue by smutel** [wekan/wekan-stats#6]
Hello,

It seams that this script is not working with private board...

In conffig.ini:
```ini
[GLOBAL]
application: WekanStats

[WEKAN_JSON]
ops-infra: https://xxxxxx/api/boards/fhQRbBE2Wad8ReAtw/export?authToken=1Bw658FVVA-EzsZd1ceYVSuYAEQjPMeASWoeE4bT-1X
```

When I launch the script:
```
INFO:WekanStats.WsMotor:Creating an instance of WsMotor
INFO:WekanStats.WsMotor:Exporting JSON Wekan URL for board "ops-infra" to a class dic : https://xxxxxx/api/boards/fhQRbBE2Wad8ReAtw/export?authToken=1Bw658FVVA-EzsZd1ceYVSuYAEQjPMeASWoeE4bT-1X
ERROR:WekanStats:RunTimeError during instance creation : u'as3xFA88p64P9jkZk'
Traceback (most recent call last):
  File "./get-stats.py", line 193, in <module>
    main()
  File "./get-stats.py", line 63, in main
    raise RuntimeError('Exception during instance creation : ' + str(e))
RuntimeError: Exception during instance creation : u'as3xFA88p64P9jkZk'
```

What is the issue ?

**Comment by yesquines** [comment]
Hello,

I'm have the same problem.

1º I used a similar configuration that **smutel** and I got the same error

2º I also tried do download the Wekan Json and put on a local webserver using the python module **ComplexHTTPServer** and changing my `config.ini`, like this:

```
[GLOBAL]
application: WekanStats

[WEKAN_JSON]
localboard: http://localhost:8000/board.json
```
And when I launch the script 
```
INFO:WekanStats.WsMotor:Creating an instance of WsMotor
INFO:WekanStats.WsMotor:Exporting JSON Wekan URL for board "localboard" to a class dic : http://localhost:8000/board.json
ERROR:WekanStats:RunTimeError during instance creation : u'mpfthvwE8fqXu9kPP'
Traceback (most recent call last):
  File "./get-stats.py", line 193, in <module>
    main()
  File "./get-stats.py", line 63, in main
    raise RuntimeError('Exception during instance creation : ' + str(e))
RuntimeError: Exception during instance creation : u'mpfthvwE8fqXu9kPP'
```

Do someone know how figure out this problem?
